services:
  frontend:
    build:
      context: ./zenco
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      API_URL: http://backend:8080
    networks:
      - app-network

  backend:
    build:
      context: ./zencoBE
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DATABASE_NAME: zencomex
      DATABASE_USER: root
      DATABASE_PASSWORD: zenco2020
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      NODE_ENV: production
      REACT_URL: https://zencomex.com/
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy
    command: ["sh", "-c", "cd /app/src && npm start"]

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: zencomex
      MYSQL_ROOT_PASSWORD: zenco2020
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 10s
      retries: 5
      start_period: 60s
      timeout: 10s

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8088:80" # Nginx sẽ sử dụng cổng 80
      - "8443:443"
    # volumes:
    #     - ./nginx/certs:/etc/letsencrypt/live/phuczenco.id.vn
    #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  backend-data:
  db_data:
